<a href="https://colab.research.google.com/github/ClaritaFlor/Machine-Learning/blob/master/Laboratorio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio Numpy
## Libreria de Python para trabajar con matrices, Numpy=Numerical Python

In [0]:
import numpy as np

In [0]:
# crear un array y mostrar
lista=[1,2,3,4]
array=np.array(lista)
array

array([1, 2, 3, 4])

In [0]:
#crear una matriz y mostrar
lista2=[[1,2,3],[4,5,6],[7,8,9]]
array2=np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
#comprobando el consumo de numpy vs python
import sys
A=range(1000)
print ("Consumo en Python")
print (sys.getsizeof(5)*len(A))
B=np.arange(1000)
print ("resultado con numpy")
print (B.size*B.itemsize)

Consumo en Python
28000
resultado con numpy
4000


In [0]:
# generar un array de 5 elementos
array3=np.arange(5)
array3

array([0, 1, 2, 3, 4])

In [0]:
#array entre 2 y 10
array4=np.arange(2,10)
array4

array([2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#array entre 10 y 20 de 2 en 2
array5=np.arange(10,20,2)
array5

array([10, 12, 14, 16, 18])

In [0]:
# array lleno de ceros
array6=np.zeros(3)
array6

array([0., 0., 0.])

In [0]:
# matriz lleno de ceros
array7=np.zeros((3,4))
array7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
# array de unos
array8=np.ones(4)
array8

array([1., 1., 1., 1.])

In [0]:
# matriz de unos
array9=np.ones((3,4))
array9

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
# array de 50 numeros aleatorios entre 5 y 8
array10=np.linspace(5,8,50)
array10

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [0]:
# array con diagonal principal
array11=np.eye(10)
array11

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [0]:
array12=np.random.rand(5)
array12

array([0.29920771, 0.21034237, 0.89305093, 0.63499841, 0.9290569 ])

In [0]:
array13=np.random.rand(4,5)
array13

array([[0.4376609 , 0.84793864, 0.91589785, 0.96525357, 0.98270275],
       [0.59045156, 0.67328179, 0.39503267, 0.42910814, 0.98541137],
       [0.78373112, 0.45619521, 0.76939242, 0.33509577, 0.07400551],
       [0.89975063, 0.76170955, 0.09841281, 0.70416482, 0.18236896]])

In [0]:
array14=np.random.randint(1,20)
array14

10

In [0]:
array15=np.random.randint(1,100,25)
array15

array([62, 15, 31, 23,  4,  7, 48, 69, 60, 30, 85,  9, 47, 72,  5, 68, 60,
       19, 25, 51, 99, 70, 20, 20, 70])

In [0]:
array16=np.random.randint(1,100,50)
array16

array([96, 88, 22, 99, 49, 65, 83, 60, 36, 98, 66,  1, 56,  8, 42, 27, 61,
       80, 29, 54, 20, 59, 75, 47, 91, 51, 26, 91,  9, 28, 15, 31, 94, 58,
       25, 87, 31, 65, 92, 81,  5, 51, 77,  5,  1, 42, 93, 43, 93, 77])

In [0]:
valor_maximo=array16.max()
valor_maximo

99

In [0]:
valor_minimo=array16.min()
valor_minimo

1

In [0]:
posicion_maximo=array16.argmax()
posicion_maximo

3

In [0]:
posicion_minimo=array16.argmin()
posicion_minimo

11

In [0]:
array17=np.arange(0,10)
array17

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
array17[0]

0

In [0]:
array17[-1]

9

In [0]:
array17[2:4]

array([2, 3])

In [0]:
array17[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
array17[5:]

array([5, 6, 7, 8, 9])

In [0]:
array17[:5]

array([0, 1, 2, 3, 4])

In [0]:
array17+array17

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
array17-array17

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
array17*array17

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])